package com.bank.bian.letterofcredit;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: Letter Of Credit
 *
 * Business Area:      Operations and Execution
 * Business Domain:    Loans and Deposits
 * Functional Pattern: Fulfill
 * Asset Type:         Letter Of Credit
 * Control Record:     Letter Of Credit Fulfillment Arrangement
 *
 * Generated by the bian-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("Letter Of Credit — BIAN Semantic API")
                .description("Service Domain 'Letter Of Credit' (Fulfill pattern) "
                        + "operating on the 'Letter Of Credit Fulfillment Arrangement' control record.")
                .version("0.1.0"));
    }
}
